"""Root page template — uses Taipy Stylekit built-in classes.

Sidebar widgets are generated by build_sidebar_section() from page_template.py.
Widget definitions are DATA (type, var, label, callback, condition).
All structural wrapping and styling is template-controlled — zero styling in definitions.
"""

from page_template import SidebarWidget, build_sidebar_section

GETTING_STARTED = """\
**Suggested workflow:**

1. **Shot Map** \u2014 shot locations and xG
2. **Match Summary** \u2014 match overview with xG, passing, pressing
3. **Player Comparison** \u2014 per-90 radar chart (1-3 players)
4. **Player Similarity** \u2014 find comparable players by style
5. **Action Values** \u2014 who contributed most? (VAEP)
6. **Defensive Impact** \u2014 pressure on attackers (DEFCON)

**Advanced pages** (tracking data, ~20 matches): \
Movement & Pressing, Pitch Control, Pass Timing (PAUSA), \
Defensive Impact.

**How to start:** Use the sidebar filters to select a competition, \
then a team and match.

Hover over the info icon on any metric for an explanation. \
Use **Glossary** for terms.
"""

GLOSSARY: dict[str, str] = {
    "xG (Expected Goals)": "Probability of scoring from each shot's location and context. Higher = better chance.",
    "Brier Score": "Prediction calibration metric. 0.0 = perfect, 0.25 = coin flip. Lower is better.",
    "VAEP": "Valuing Actions by Estimating Probabilities \u2014 how much each on-ball action changed scoring probability.",
    "VAEP/90": "VAEP per 90 minutes played. Higher = more impactful player.",
    "PPDA": "Passes Per Defensive Action. Lower = more aggressive pressing. Range: 5\u201315.",
    "Pitch Control": "Physics-based model estimating which team controls each pitch location (Spearman 2017).",
    "PAUSA": "Passing Ability Under Spatiotemporal Awareness. Temporal judgment \u00d7 spatial selection. Higher = better.",
    "Temporal Judgment": "Was the pass released at the optimal moment? 1.0 = perfect timing.",
    "Spatial Selection": "Was the target location the best available? 1.0 = optimal target.",
    "OBSO": "Off-Ball Scoring Opportunity. Pitch Control \u00d7 Transition \u00d7 EPV (Spearman 2018).",
    "DEFCON": "Defensive Contribution framework (Kim et al. 2025). 4 credit categories.",
    "Intercept": "DEFCON credit for winning the ball. Higher = more successful interceptions.",
    "Concede": "DEFCON credit when a shot/goal occurs despite pressure. Lower is better.",
    "Disturb": "DEFCON credit for disrupting possession without winning the ball.",
    "Deter": "DEFCON credit for preventing attacker progression through positioning.",
    "Cosine Distance": "Player similarity measure. 0.0 = identical style, 1.0 = completely different.",
    "xT (Expected Threat)": "Probability that ball possession in a pitch zone leads to a goal within next few actions.",
    "Off-Ball xT": "Expected threat from a player's off-ball movement. Typical range: 0.001\u20130.01 per match.",
    "Line-Breaking Pass": "A pass that penetrates at least one defensive line (Ward clustering on 360 freeze frames).",
    "Progressive Pass": "A pass moving the ball significantly closer to the opponent's goal.",
    "SPADL": "Soccer Player Action Description Language \u2014 23 canonical action types (105\u00d768m coordinates).",
}

PAGE_TERMS: dict[str, list[str]] = {
    "Shot-Map": ["xG (Expected Goals)", "Brier Score"],
    "Pass-Map": ["Line-Breaking Pass", "Progressive Pass"],
    "Heat-Map": [],
    "Pass-Network": [],
    "Match-Summary": ["xG (Expected Goals)", "PPDA", "Progressive Pass"],
    "Player-Impact": ["VAEP", "VAEP/90", "SPADL"],
    "Player-Comparison": [
        "xG (Expected Goals)",
        "VAEP",
        "VAEP/90",
        "PPDA",
        "xT (Expected Threat)",
        "Off-Ball xT",
        "DEFCON",
        "Line-Breaking Pass",
        "Progressive Pass",
    ],
    "Player-Similarity": ["Cosine Distance"],
    "Movement-Pressing": ["PPDA", "xT (Expected Threat)", "Off-Ball xT", "Pitch Control"],
    "Pitch-Control": ["Pitch Control"],
    "Pass-Timing": ["PAUSA", "Temporal Judgment", "Spatial Selection", "OBSO"],
    "Defensive-Impact": ["DEFCON", "Intercept", "Concede", "Disturb", "Deter"],
}


def get_glossary_md(page_name: str) -> str:
    """Return filtered glossary as HTML for the current page."""
    if page_name in PAGE_TERMS:
        terms = PAGE_TERMS[page_name]
        filtered = {k: v for k, v in GLOSSARY.items() if k in terms}
    else:
        filtered = GLOSSARY
    if not filtered:
        return "<p style='opacity:0.5'>No domain-specific terms on this page.</p>"
    lines = []
    for k, v in filtered.items():
        lines.append(f"<p><strong>{k}</strong> \u2014 {v}</p>")
    return "".join(lines)


# fmt: off
_COMP_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary", "Player-Impact", "Player-Comparison", "Movement-Pressing")
_TEAM_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary", "Player-Impact", "Player-Comparison")
_MATCH_PAGES = ("Pass-Map", "Pass-Network", "Match-Summary", "Player-Impact")
_PLAYER_PAGES = ("Shot-Map", "Heat-Map", "Player-Impact")
_PLAYER_MULTI_PAGES = ("Player-Comparison",)
_XG_MODEL_PAGES = ("Shot-Map",)
_MIN_PASSES_PAGES = ("Pass-Network",)
_MIN_MINUTES_PAGES = ("Player-Impact", "Player-Comparison")
_PROVIDER_PAGES = ("Movement-Pressing", "Pitch-Control")
_TRACKING_PAGES = ("Movement-Pressing", "Pitch-Control")
_SUB_VIEW_PAGES = ("Player-Impact", "Movement-Pressing")
_PASS_OVERLAY_PAGES = ("Pass-Map",)
_SIMILARITY_PAGES = ("Player-Similarity",)
_PASS_TIMING_PAGES = ("Pass-Timing",)
_DEFCON_PAGES = ("Defensive-Impact",)
_PC_CONTROL_PAGES = ("Pitch-Control",)
_FILTER_HEADER_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary",
                        "Player-Impact", "Player-Comparison", "Movement-Pressing",
                        "Pitch-Control", "Pass-Timing", "Defensive-Impact")
# fmt: on

# ---------------------------------------------------------------------------
# Sidebar widget definitions — DATA ONLY, zero styling.
# build_sidebar_section() handles all structural wrapping and CSS.
# ---------------------------------------------------------------------------

_FILTER_WIDGETS: list[SidebarWidget] = [
    SidebarWidget(
        "dropdown",
        "selected_competition",
        "Competition",
        "on_competition_change",
        condition=f"current_page in {_COMP_PAGES}",
        lov="competition_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_team",
        "Team",
        "on_team_change",
        condition=f"current_page in {_TEAM_PAGES}",
        lov="team_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_match",
        "Match",
        "on_match_change",
        condition=f"current_page in {_MATCH_PAGES}",
        lov="match_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_player",
        "Player",
        "on_player_change",
        condition=f"current_page in {_PLAYER_PAGES}",
        lov="player_lov",
    ),
    SidebarWidget(
        "dropdown_multi",
        "selected_players_multi",
        "Players (1-3)",
        "on_player_change",
        condition=f"current_page in {_PLAYER_MULTI_PAGES}",
        lov="player_lov_multi",
    ),
    SidebarWidget(
        "dropdown",
        "pr_selected_metrics",
        "Metrics",
        "on_pr_metric_change",
        condition=f"current_page in {('Player-Comparison',)}",
        lov="pr_metric_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_xg_model",
        "xG Model",
        "on_xg_model_change",
        condition=f"current_page in {_XG_MODEL_PAGES}",
        lov="xg_model_lov",
    ),
    SidebarWidget(
        "slider",
        "min_passes",
        "Min. passes per connection",
        "on_min_passes_change",
        condition=f"current_page in {_MIN_PASSES_PAGES}",
        slider_min="1",
        slider_max="10",
        slider_range_labels=("1", "10"),
    ),
    SidebarWidget(
        "slider",
        "min_minutes",
        "Min. minutes played",
        "on_min_minutes_change",
        condition=f"current_page in {_MIN_MINUTES_PAGES}",
        slider_min="0",
        slider_max="2000",
        slider_step="45",
        slider_range_labels=("0", "2000"),
    ),
    SidebarWidget(
        "toggle",
        "pm_show_progressive",
        "Progressive passes",
        "on_pm_toggle_change",
        condition=f"current_page in {_PASS_OVERLAY_PAGES}",
    ),
    SidebarWidget(
        "toggle",
        "pm_show_line_breaking",
        "Line-breaking passes",
        "on_pm_toggle_change",
        condition=f"current_page in {_PASS_OVERLAY_PAGES}",
    ),
    # Tracking / provider
    SidebarWidget(
        "dropdown",
        "selected_provider",
        "Provider",
        "on_provider_change",
        condition=f"current_page in {_PROVIDER_PAGES}",
        lov="provider_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_tracking_match",
        "Tracking Match",
        "on_tracking_match_change",
        condition=f"current_page in {_TRACKING_PAGES}",
        lov="tracking_match_lov",
    ),
    SidebarWidget(
        "dropdown",
        "selected_sub_view",
        "View",
        "on_sub_view_change",
        condition=f"current_page in {_SUB_VIEW_PAGES}",
        lov="sub_view_lov",
    ),
    # Pass Timing
    SidebarWidget(
        "dropdown",
        "pt_selected_match",
        "PAUSA Match",
        "pt_on_match_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_match_lov",
    ),
    SidebarWidget(
        "dropdown",
        "pt_selected_team",
        "Team (optional)",
        "pt_on_team_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_team_lov",
    ),
    SidebarWidget(
        "dropdown",
        "pt_selected_player",
        "Player (optional)",
        "pt_on_player_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_player_lov",
    ),
    # Defensive Impact
    SidebarWidget(
        "dropdown",
        "dv_selected_comp",
        "Competition (DEFCON)",
        "dv_on_comp_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_comp_lov",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_team",
        "Team (optional)",
        "dv_on_team_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_team_lov",
    ),
    SidebarWidget(
        "dropdown",
        "dv_current_view",
        "View",
        "dv_on_view_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_view_lov",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_breakdown_player",
        "Player",
        "dv_on_breakdown_player_change",
        condition='current_page == "Defensive-Impact" and dv_current_view == "Breakdown" and len(dv_breakdown_player_lov) > 0',
        lov="dv_breakdown_player_lov",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_timeline_player",
        "Player",
        "dv_on_timeline_player_change",
        condition='current_page == "Defensive-Impact" and dv_current_view == "Timeline" and len(dv_timeline_player_lov) > 0',
        lov="dv_timeline_player_lov",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_timeline_match",
        "Match",
        "dv_on_timeline_match_change",
        condition='current_page == "Defensive-Impact" and dv_current_view == "Timeline" and len(dv_timeline_match_lov) > 0',
        lov="dv_timeline_match_lov",
    ),
    # Pitch Control
    SidebarWidget(
        "dropdown",
        "pc_half",
        "Half",
        "pc_on_half_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
        lov="pc_half_lov",
    ),
    SidebarWidget(
        "dropdown",
        "pc_model",
        "Model",
        "pc_on_model_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
        lov="pc_model_lov",
    ),
    SidebarWidget(
        "toggle",
        "pc_show_velocity",
        "Show velocity arrows",
        "pc_on_velocity_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
    ),
    SidebarWidget(
        "slider",
        "pc_elapsed_seconds",
        "Time",
        "pc_on_seconds_change",
        condition=f"current_page in {_PC_CONTROL_PAGES} and pc_max_seconds > 1",
        slider_min="0",
        slider_max="2700",
        filter_box_label="<|{pc_time_label}|text|raw|>",
        slider_range_labels=("0:00", ""),
        slider_range_vars=("", "pc_max_time_display"),
    ),
    # Player Similarity compare
    SidebarWidget(
        "dropdown",
        "ps_selected_compare",
        "Compare with",
        "on_ps_selected_compare_change",
        condition='current_page == "Player-Similarity" and len(ps_results_data) > 0',
        lov="ps_compare_lov",
    ),
]

_SEARCH_WIDGETS: list[SidebarWidget] = [
    SidebarWidget("dropdown", "ps_search_mode", "Search by", "on_ps_search_mode_change", lov="ps_search_mode_lov"),
    SidebarWidget("dropdown", "ps_selected_player", "Player", "on_ps_selected_player_change", lov="ps_player_lov"),
    SidebarWidget("dropdown", "ps_result_count", "Results", "on_ps_result_count_change", lov="ps_result_count_lov"),
    SidebarWidget("toggle", "ps_filter_by_competition", "Filter by competition", "on_ps_filter_by_competition_change"),
    SidebarWidget(
        "dropdown",
        "ps_selected_competition",
        "Competition",
        "on_ps_selected_competition_change",
        condition="ps_filter_by_competition",
        lov="ps_competition_lov",
    ),
]

# Generate sidebar sections from widget definitions
_filter_section = build_sidebar_section(
    "Filters", _FILTER_WIDGETS, condition=f"current_page in {_FILTER_HEADER_PAGES}", f_string=False
)
_search_section = build_sidebar_section(
    "Search", _SEARCH_WIDGETS, condition=f"current_page in {_SIMILARITY_PAGES}", f_string=False
)

root_page = f"""
<|layout|columns=300px 1fr|gap=0.75rem|

<|part|class_name=sidebar|

<|part|class_name=ll-nav-header|
**Match Analysis**
|>

[<span class="material-symbols-outlined">target</span> Shot Map](/Shot-Map)

[<span class="material-symbols-outlined">arrow_forward</span> Pass Map](/Pass-Map)

[<span class="material-symbols-outlined">local_fire_department</span> Heat Map](/Heat-Map)

[<span class="material-symbols-outlined">hub</span> Pass Network](/Pass-Network)

[<span class="material-symbols-outlined">scoreboard</span> Match Summary](/Match-Summary)

<|part|class_name=ll-nav-header|
**Player Analysis**
|>

[<span class="material-symbols-outlined">trending_up</span> Player Impact](/Player-Impact)

[<span class="material-symbols-outlined">radar</span> Player Comparison](/Player-Comparison)

[<span class="material-symbols-outlined">search</span> Player Similarity](/Player-Similarity)

<|part|class_name=ll-nav-header|
**Advanced**
|>

[<span class="material-symbols-outlined">directions_run</span> Movement & Pressing](/Movement-Pressing)

[<span class="material-symbols-outlined">grid_on</span> Pitch Control](/Pitch-Control)

[<span class="material-symbols-outlined">timer</span> Pass Timing](/Pass-Timing)

[<span class="material-symbols-outlined">shield</span> Defensive Impact](/Defensive-Impact)

{_filter_section}
{_search_section}

|>

<|part|

<|part|class_name=ll-title-row|
<|layout|columns=1fr auto auto|gap=0.5rem|class_name=align-columns-center|

<|part|class_name=ll-brand|
# <span class="material-symbols-outlined">sports_soccer</span> (Right! Luxury!) Lakehouse
|>

<|Glossary|button|class_name=text-no-transform ll-header-btn ll-btn-glossary|on_action=toggle_glossary|>

<|Getting Started|button|class_name=text-no-transform ll-header-btn ll-btn-started|on_action=toggle_getting_started|>

|>
|>

<|part|render={{show_glossary and current_page == "Shot-Map"}}|class_name=ll-dropdown|
**xG (Expected Goals)** \u2014 Probability of scoring from each shot's location and context. Higher = better chance.

**Brier Score** \u2014 Prediction calibration metric. 0.0 = perfect, 0.25 = coin flip. Lower is better.
|>

<|part|render={{show_glossary and current_page == "Pass-Map"}}|class_name=ll-dropdown|
**Line-Breaking Pass** \u2014 A pass that penetrates at least one defensive line (Ward clustering on 360 freeze frames).

**Progressive Pass** \u2014 A pass moving the ball significantly closer to the opponent's goal.
|>

<|part|render={{show_glossary and current_page == "Heat-Map"}}|class_name=ll-dropdown|
*No domain-specific terms on this page.*
|>

<|part|render={{show_glossary and current_page == "Pass-Network"}}|class_name=ll-dropdown|
*No domain-specific terms on this page.*
|>

<|part|render={{show_glossary and current_page == "Match-Summary"}}|class_name=ll-dropdown|
**xG (Expected Goals)** \u2014 Probability of scoring from each shot's location and context. Higher = better chance.

**PPDA** \u2014 Passes Per Defensive Action. Lower = more aggressive pressing. Range: 5\u201315.

**Progressive Pass** \u2014 A pass moving the ball significantly closer to the opponent's goal.
|>

<|part|render={{show_glossary and current_page == "Player-Impact"}}|class_name=ll-dropdown|
**VAEP** \u2014 Valuing Actions by Estimating Probabilities \u2014 how much each on-ball action changed scoring probability.

**VAEP/90** \u2014 VAEP per 90 minutes played. Higher = more impactful player.

**SPADL** \u2014 Soccer Player Action Description Language \u2014 23 canonical action types (105\u00d768m coordinates).
|>

<|part|render={{show_glossary and current_page == "Player-Comparison"}}|class_name=ll-dropdown|
**xG (Expected Goals)** \u2014 Probability of scoring from each shot's location and context. Higher = better chance.

**VAEP** \u2014 Valuing Actions by Estimating Probabilities \u2014 how much each on-ball action changed scoring probability.

**PPDA** \u2014 Passes Per Defensive Action. Lower = more aggressive pressing.

**xT (Expected Threat)** \u2014 Probability that ball possession in a pitch zone leads to a goal within next few actions.

**Off-Ball xT** \u2014 Expected threat from a player's off-ball movement. Typical range: 0.001\u20130.01 per match.

**DEFCON** \u2014 Defensive Contribution framework (Kim et al. 2025). 4 credit categories.

**Line-Breaking Pass** \u2014 A pass that penetrates at least one defensive line.

**Progressive Pass** \u2014 A pass moving the ball significantly closer to the opponent's goal.
|>

<|part|render={{show_glossary and current_page == "Player-Similarity"}}|class_name=ll-dropdown|
**Cosine Distance** \u2014 Similarity measure between player embedding vectors. 0.0 = identical style, 1.0 = completely different.
|>

<|part|render={{show_glossary and current_page == "Movement-Pressing"}}|class_name=ll-dropdown|
**PPDA** \u2014 Passes Per Defensive Action. Lower = more aggressive pressing.

**xT (Expected Threat)** \u2014 Probability that ball possession in a pitch zone leads to a goal within next few actions.

**Off-Ball xT** \u2014 Expected threat from a player's off-ball movement. Typical range: 0.001\u20130.01 per match.

**Pitch Control** \u2014 Physics-based model estimating which team controls each pitch location (Spearman 2017).
|>

<|part|render={{show_glossary and current_page == "Pitch-Control"}}|class_name=ll-dropdown|
**Pitch Control** \u2014 Physics-based model estimating which team controls each pitch location (Spearman 2017).
|>

<|part|render={{show_glossary and current_page == "Pass-Timing"}}|class_name=ll-dropdown|
**PAUSA** \u2014 Passing Ability Under Spatiotemporal Awareness. Temporal judgment \u00d7 spatial selection. Higher = better.

**Temporal Judgment** \u2014 Was the pass released at the optimal moment? 1.0 = perfect timing.

**Spatial Selection** \u2014 Was the target location the best available? 1.0 = optimal target.

**OBSO** \u2014 Off-Ball Scoring Opportunity. Pitch Control \u00d7 Transition \u00d7 EPV (Spearman 2018).
|>

<|part|render={{show_glossary and current_page == "Defensive-Impact"}}|class_name=ll-dropdown|
**DEFCON** \u2014 Defensive Contribution framework (Kim et al. 2025). 4 credit categories.

**Intercept** \u2014 DEFCON credit for winning the ball. Higher = more successful interceptions.

**Concede** \u2014 DEFCON credit when a shot/goal occurs despite pressure. Lower is better.

**Disturb** \u2014 DEFCON credit for disrupting possession without winning the ball.

**Deter** \u2014 DEFCON credit for preventing attacker progression through positioning.
|>

<|part|render={{show_getting_started}}|class_name=ll-dropdown|
{GETTING_STARTED}
|>

<|part|render={{is_loading}}|class_name=ll-loading-overlay|
<|part|class_name=ll-loading-spinner|
<span class="material-symbols-outlined ll-spin">progress_activity</span> Loading...
|>
|>

<|content|>

<|part|class_name=ll-footer|
|>

|>

|>
"""
