-- scripts/migrations/2026-05-28-create-spadl-action-context.sql
--
-- AC-1 unified action context table — one row per SPADL action, all providers.
--
-- Idempotent (CREATE TABLE IF NOT EXISTS); auto-applied by
-- .github/workflows/dbt-live-ci.yml "Apply pending bronze migrations" step.
--
-- CDF enabled from birth per spec §8.1; liquid clustering + autoOptimize
-- per lakehouse mart-table defaults.
--
-- Catalog hardcoded as `soccer_analytics` per existing migration convention.

CREATE TABLE IF NOT EXISTS soccer_analytics.bronze.spadl_action_context (
  data_source STRING,
  match_id STRING,
  action_id BIGINT,
  period_id BIGINT,
  time_seconds DOUBLE,
  team_id STRING,
  player_id STRING,
  type_name STRING,
  start_x DOUBLE,
  start_y DOUBLE,
  end_x DOUBLE,
  end_y DOUBLE,
  game_state STRING,
  frame_id BIGINT,
  time_offset_seconds DOUBLE,
  link_quality_score DOUBLE,
  n_candidate_frames BIGINT,
  defending_gk_player_id_native STRING,
  gk_was_distributing BOOLEAN,
  gk_was_engaged BOOLEAN,
  gk_actions_in_possession BIGINT,
  pre_shot_gk_x DOUBLE,
  pre_shot_gk_y DOUBLE,
  pre_shot_gk_distance_to_goal DOUBLE,
  pre_shot_gk_distance_to_shot DOUBLE,
  pre_shot_gk_angle_to_shot_trajectory DOUBLE,
  pre_shot_gk_angle_off_goal_line DOUBLE,
  nearest_defender_distance DOUBLE,
  actor_speed DOUBLE,
  receiver_zone_density BIGINT,
  defenders_in_triangle_to_goal BIGINT,
  actor_arc_length_pre_window DOUBLE,
  actor_displacement_pre_window DOUBLE,
  pressure_on_actor__andrienko_oval DOUBLE,
  pressure_on_actor__link_zones DOUBLE,
  pressure_on_actor__bekkers_pi DOUBLE,
  pitch_control_at_ball__spearman DOUBLE,
  pitch_control_at_ball__fernandez_bornn DOUBLE,
  pitch_control_at_ball__voronoi DOUBLE,
  defensive_line_x DOUBLE,
  back_line_high_x DOUBLE,
  compactness_x DOUBLE,
  lateral_width DOUBLE,
  max_lateral_gap DOUBLE,
  back_n_count BIGINT,
  line_break BOOLEAN,
  n_attackers_behind_line BIGINT,
  n_off_ball_runners_pre_window BIGINT,
  max_off_ball_run_displacement_pre_window DOUBLE,
  mean_off_ball_run_speed_pre_window DOUBLE,
  n_off_ball_runners_toward_goal_pre_window BIGINT,
  line_break__ward BOOLEAN,
  lines_broken__ward BIGINT,
  line_breaking_type__ward STRING,
  team_shape_centroid_x_attacking DOUBLE,
  team_shape_centroid_y_attacking DOUBLE,
  team_shape_convex_hull_area_attacking DOUBLE,
  team_shape_team_length_attacking DOUBLE,
  team_shape_team_width_attacking DOUBLE,
  team_shape_stretch_index_attacking DOUBLE,
  team_shape_n_outfield_players_attacking BIGINT,
  team_shape_centroid_x_defending DOUBLE,
  team_shape_centroid_y_defending DOUBLE,
  team_shape_convex_hull_area_defending DOUBLE,
  team_shape_team_length_defending DOUBLE,
  team_shape_team_width_defending DOUBLE,
  team_shape_stretch_index_defending DOUBLE,
  team_shape_n_outfield_players_defending BIGINT,
  das_team DOUBLE,
  das_opponent DOUBLE,
  das_diff DOUBLE,
  gk_pitch_control_share_weighted DOUBLE,
  gk_reachable_area_m2 DOUBLE,
  gk_closing_time_mean_s__six_yard_box DOUBLE,
  gk_closing_time_min_s__six_yard_box DOUBLE,
  n_blocked_receivers BIGINT,
  n_potential_receivers BIGINT,
  blocking_score DOUBLE,
  blocked_threat_fraction DOUBLE,
  max_single_defender_blocking_score DOUBLE,
  sync_score_min DOUBLE,
  sync_score_mean DOUBLE,
  sync_score_high_quality_frac DOUBLE,
  obso_actual DOUBLE,
  obso_peak DOUBLE,
  obso_optimal DOUBLE,
  pausa_temporal DOUBLE,
  pausa_spatial DOUBLE,
  pausa_composite DOUBLE,
  space_created_m2_team DOUBLE,
  space_created_m2_opponent DOUBLE,
  elastic_frame_id BIGINT,
  elastic_confidence DOUBLE,
  elastic_error_seconds DOUBLE,
  shape_graph_density_attacking DOUBLE,
  shape_graph_n_edges_attacking BIGINT,
  shape_graph_mean_stability_attacking DOUBLE,
  shape_graph_density_defending DOUBLE,
  shape_graph_n_edges_defending BIGINT,
  shape_graph_mean_stability_defending DOUBLE,
  _ingested_at TIMESTAMP
)
USING DELTA
TBLPROPERTIES (
  delta.enableChangeDataFeed = 'true',
  delta.autoOptimize.optimizeWrite = 'true',
  delta.autoOptimize.autoCompact = 'true'
);
