"""Root page template — uses Taipy Stylekit built-in classes.

Exports build_root_page(nav_md) which constructs the full root page shell.
Navigation is injected via the nav_md parameter (generated by page_template.build_nav()).
Sidebar widgets are generated by build_sidebar_section() from page_template.py.
Widget definitions are DATA (type, var, label, callback, condition).
All structural wrapping and styling is template-controlled — zero styling in definitions.
"""

from page_template import (
    _FOOTER_CONTENT,
    SidebarWidget,
    build_sidebar_section,
)

GETTING_STARTED = """\
**Suggested workflow:**

1. **Shot Map** \u2014 shot locations and xG
2. **Match Summary** \u2014 match overview with xG, passing, pressing
3. **Player Comparison** \u2014 per-90 radar chart (1-3 players)
4. **Player Similarity** \u2014 find comparable players by style
5. **Player Impact** \u2014 who contributed most? (VAEP)
6. **Defensive Impact** \u2014 pressure on attackers (DEFCON)

**Advanced pages** (tracking data, ~20 matches): \
Movement & Pressing, Pitch Control, Team Shape, \
Pass Timing (PAUSA), Defensive Impact.

**How to start:** Use the sidebar filters to select a competition, \
then a team and match.

Hover over the info icon on any metric for an explanation. \
Use **Glossary** for terms.
"""

GLOSSARY: dict[str, str] = {
    "Bubble Map": (
        "Action density visualization where bubble area at each pitch zone represents "
        "the number of actions. Spatial binning approach per Anzer & Bauer (2021)."
    ),
    "Hotspot": (
        "A pitch zone with the highest action density. Heat Map highlights the top 5 zones "
        "with gold rings in the 'Hotspots' view."
    ),
    "Action Type": (
        "The kind of on-ball action — pass, shot, dribble, etc. Heat Map separates passes "
        "and shots into distinct panels."
    ),
    "xG (Expected Goals)": (
        "Probability of scoring from each shot's location and context. "
        "Higher = better chance. Sum over a match = team's expected output."
    ),
    "xG (v2 Set Encoder)": (
        "Expected goal probability from the v2 Set Encoder model with MC dropout 95% CI. "
        "Range 0-1. xg_ci_upper - xg_ci_lower = model uncertainty. "
        "Reference: Gal & Ghahramani 2016 (Dropout as Bayesian Approximation)."
    ),
    "Brier Score": (
        "Prediction calibration metric. 0.0 = perfect, 0.25 = coin flip. Lower is better. Good models score < 0.10."
    ),
    "VAEP": (
        "Valuing Actions by Estimating Probabilities \u2014 how much each on-ball action changed scoring probability."
    ),
    "VAEP/90": "VAEP per 90 minutes played. Higher = more impactful player.",
    "Off. VAEP/90": (
        "Offensive VAEP per 90 minutes \u2014 how much a player's actions increase "
        "their team's scoring probability. Higher = stronger offensive contribution."
    ),
    "Def. VAEP/90": (
        "Defensive VAEP per 90 minutes \u2014 how much a player's actions reduce "
        "the opponent's scoring probability. Higher = stronger defensive contribution."
    ),
    "PPDA": (
        "Passes Per Defensive Action \u2014 measures pressing intensity. "
        "Lower = more aggressive pressing. Range: 5\u201315."
    ),
    "Pitch Control": "Physics-based model estimating which team controls each pitch location (Spearman 2017).",
    "PAUSA": (
        "Passing Ability Under Spatiotemporal Awareness. Temporal judgment \u00d7 spatial selection. Higher = better."
    ),
    "Temporal Judgment": (
        "Was the pass released at the optimal moment? Ratio of actual OBSO at release "
        "to peak OBSO in the \u00b13s/+1s window. 1.0 = perfect timing."
    ),
    "Spatial Selection": "Was the target location the best available? 1.0 = optimal target.",
    "OBSO": "Off-Ball Scoring Opportunity. Pitch Control \u00d7 Transition \u00d7 EPV (Spearman 2018).",
    "DEFCON": (
        "Defensive Contribution framework (Kim et al. 2025). Quantifies how defenders "
        "affect an attacker's scoring probability via four credit categories."
    ),
    "Intercept": "DEFCON credit for winning the ball. Higher = more successful interceptions.",
    "Concede": "DEFCON credit when a shot/goal occurs despite pressure. Lower is better.",
    "Disturb": "DEFCON credit for disrupting possession without winning the ball.",
    "Deter": "DEFCON credit for preventing attacker progression through positioning.",
    "Conversion Rate": "The percentage of events at one funnel stage that progress to the next stage. Higher = more efficient progression through the attack.",
    "Cosine Distance": "Player similarity measure. 0.0 = identical style, 1.0 = completely different.",
    "A3 Entry": "A successful action (pass, dribble, or carry) that crosses from outside the attacking third into the final 35 meters of the pitch. Measures territorial penetration.",
    "Behavioral Vector": (
        "128-dimensional embedding from a transformer encoder trained on SPADL action sequences. "
        "Captures playing style — movement patterns, decision sequences, and positional tendencies. "
        "Adversarially debiased to remove team-specific confounds (Ganin GRL)."
    ),
    "Statistical Vector": (
        "13-dimensional vector of per-90 statistics (goals, assists, xG, passes, VAEP, etc.) "
        "z-score normalized within position group (GK, Def, Mid, Fwd). "
        "Captures volume and efficiency independent of playing style."
    ),
    "xT (Expected Threat)": "Probability that ball possession in a pitch zone leads to a goal within next few actions.",
    "Off-Ball xT": "Expected threat from a player's off-ball movement. Typical range: 0.001\u20130.01 per match.",
    "Line-Breaking Pass": (
        "A pass that penetrates at least one defensive line, detected via Ward clustering "
        "on StatsBomb 360 freeze-frame defender positions."
    ),
    "Progressive Pass": (
        "A pass moving the ball significantly closer to the opponent's goal \u2014 "
        "defined by a minimum distance threshold toward the goal line."
    ),
    "SPADL": "Soccer Player Action Description Language \u2014 23 canonical action types (105\u00d768m coordinates).",
    "Goals/90": "Goals scored per 90 minutes played. Direct scoring output.",
    "Passes/90": "Completed passes per 90 minutes played.",
    "Pass %": "Pass completion rate \u2014 percentage of attempted passes successfully completed.",
    "xG Over-performance": (
        "Goals minus xG. Positive = scored more than expected (clinical finishing). Negative = underperformed chances."
    ),
    "Our Verdict": (
        "Editorial interpretation of whether the scoreline reflected the run of play, "
        "derived from xG margin. Closed set of five phrases mapped to xG-delta thresholds."
    ),
    "Big Story": (
        "The single most decisive action of the match by VAEP impact \u2014 highlighted as "
        "the hero card of the Match Summary decisive-moments row."
    ),
    "Fully merited": ("A win where the winner's xG exceeded the loser's by at least 0.5 \u2014 clear xG dominance."),
    "Fair result": ("A match where the two teams' xG were within 0.3 \u2014 no clear xG advantage either way."),
    "Fortunate": ("A win where the winner's xG was below the loser's but the gap was narrow (< 1.5)."),
    "Smash & grab": (
        "A win where the loser's xG was significantly higher (gap \u2265 1.5) \u2014 result against the run of play."
    ),
    "Flattered by scoreline": (
        "A win where the winner's xG was at least twice their goals scored \u2014 "
        "xG suggests the scoreline underrepresents their dominance."
    ),
    "DEFCON/90": (
        "Defensive pressure received per 90 minutes (DEFCON framework). Higher = more defensive attention attracted."
    ),
    "Most Active Zone": "The 3x3 pitch zone (e.g., 'Att Center') with the highest action count.",
    "Cost Tier": (
        "How cost data was sourced: Actual (from billing), Estimated (from pipeline timing), "
        "or Projected (from YAML card estimates)."
    ),
    "Freshness SLA": (
        "Maximum acceptable age (in hours) for a workflow's output data. "
        "Green = within SLA, yellow = 75-100%, red = exceeded."
    ),
    "Workflow Card": (
        "A YAML manifest describing an AI/ML workflow — its inputs, outputs, execution config, "
        "cost estimates, and academic provenance."
    ),
    "Workflow Status": (
        "The state of a workflow's most recent run. "
        "COMPLETED = last run succeeded. RUNNING = executing now. "
        "FAILED = last run errored. SKIPPED = last run was skipped."
    ),
    "Trigger": ("How a workflow is initiated. Scheduled = runs on a cron interval. Manual = triggered by a human."),
    "Cold Start": (
        "Serverless environment setup time before pipeline work begins. "
        "Includes compute spin-up, wheel installation, and Python imports. Lower is better."
    ),
    "Entities": (
        "Average number of input entities (e.g., matches, players) processed per run. "
        "From the pipeline's skip guard, which determines what work is needed."
    ),
    "Passes with Value": (
        "Passes where the off-ball scoring opportunity (actual OBSO) was greater than zero. "
        "Used as a quality proxy for 'successful' passes when pass outcome data is unavailable."
    ),
    "Percentile Rank": (
        "Where a player's metric sits relative to all other players in the same competition "
        "(0-1 scale, 1.0 = top of competition)."
    ),
    "Team Shape": "Spatial metrics describing how a team is spread across the pitch — length, width, hull area, stretch index.",
    "Convex Hull": "Smallest polygon enclosing all outfield players. Area indicates territorial extent (~1,000 m² defending, ~1,500 m² attacking).",
    "Stretch Index": "Mean distance of all outfield players from the team centroid (Bourbousson et al. 2010). Lower = more compact.",
    "EFPI": "Elastic Formation and Position Identification — template matching algorithm for automatic formation detection (Bekkers & Dabadghao 2025).",
    "Shape Graph": "Delaunay-based geometric formation detection -- builds a stable proximity graph from player positions without formation templates (Sotudeh 2026).",
    "Defensive Line Height": "Average position of the defensive line as % of pitch length. 0% = own goal, 100% = opponent goal.",
    "Inter-Line Gaps": "Distance between defensive-midfield and midfield-attack line centroids. Under 12m = compact, over 18m = exposed.",
    "Team Length": "Distance between deepest and most advanced outfield players along the goal-to-goal axis.",
    "Team Width": "Distance between widest outfield players along the touchline-to-touchline axis.",
    "PSxG (Post-Shot Expected Goals)": (
        "Probability of a shot being scored given its end location in the goal frame "
        "(0-1 per shot, higher = harder to save). Normalized per 90 minutes for cross-GK comparison."
    ),
    "Goals Prevented": (
        "PSxG faced minus goals conceded, normalized per 90 minutes. "
        "Positive = GK saved more than the model expected. Negative = conceded more than expected."
    ),
    "Launch Rate": "Percentage of GK distribution passes over 60m. Higher = more direct style. Typical range: 15-40%.",
    "xT / Pass (Distribution)": (
        "Average Expected Threat gained per GK distribution pass. "
        "Higher = more progressive distribution (typical: 0.001\u20130.005)."
    ),
    "Save %": (
        "Percentage of on-target shots saved. Higher = better shot-stopping. "
        "Only available for competitions with tracking data."
    ),
    "Claim Success %": (
        "Successful claims divided by total claim attempts. "
        "A claim is when the GK comes to catch a cross or high ball. Higher = more reliable claiming."
    ),
    "Sweeper Distance": (
        "Average distance (meters) of GK defensive actions from own goal line. "
        "Higher = more proactive sweeper style. Typical range: 8-15m."
    ),
    "Outside Box/90": (
        "Defensive actions outside the penalty area per 90 minutes. "
        "Higher = more involved in outfield play. Typical range: 0.5-2.0."
    ),
    "Possession": "A continuous sequence of on-ball actions by one team, ending when the opposing team gains control. StatsBomb definition.",
    "Position Label": (
        "Combined tactical role (e.g., RCB, LWB, CAM) from vertical level (B/DM/M/AM/F) "
        "and horizontal level (L/LC/C/RC/R)."
    ),
    "Vertical Level": (
        "Depth classification of a player's position: Back (B), Defensive Midfield (DM), "
        "Midfield (M), Attacking Midfield (AM), Forward (F)."
    ),
    "Horizontal Level": "Width classification: Left (L), Left-Center (LC), Center (C), Right-Center (RC), Right (R).",
    "Position Map": (
        "5x5 grid showing percentage of time a player occupies each tactical role combination "
        "(vertical level x horizontal level)."
    ),
    "Formation Detector": (
        "Algorithm that assigns formation labels (e.g., 4-3-3) to player positioning data. "
        "EFPI uses template matching; Shape Graph uses Delaunay triangulation."
    ),
    "Passing Network": (
        "Graph of passing connections between teammates. Node = player positioned at their "
        "average x/y location during the match; edge = pass between two players; line thickness = pass frequency."
    ),
    "Average Position": (
        "Mean (x, y) location of a player during the match — summarizes where they touched the ball. "
        "Used as the node coordinate in the pass network."
    ),
    "Pass Connection": (
        "An edge in the pass network between two teammates. Filtered to connections with "
        "at least min_passes (default 3) to avoid clutter."
    ),
}

PAGE_TERMS: dict[str, list[str]] = {
    "Shot-Map": ["xG (Expected Goals)", "xG (v2 Set Encoder)", "Brier Score"],
    "Pass-Map": ["Line-Breaking Pass", "Progressive Pass"],
    "Heat-Map": ["Bubble Map", "Hotspot", "Action Type"],
    "Pass-Network": ["Passing Network", "Average Position", "Pass Connection"],
    "Match-Summary": [
        "xG (Expected Goals)",
        "PPDA",
        "VAEP",
        "Progressive Pass",
        "Our Verdict",
        "Big Story",
        "Fully merited",
        "Fair result",
        "Fortunate",
        "Smash & grab",
        "Flattered by scoreline",
    ],
    "Player-Impact": ["VAEP", "VAEP/90", "Off. VAEP/90", "Def. VAEP/90", "SPADL", "Percentile Rank"],
    "Player-Comparison": [
        "Goals/90",
        "xG (Expected Goals)",
        "xG Over-performance",
        "Passes/90",
        "Pass %",
        "Progressive Pass",
        "Line-Breaking Pass",
        "VAEP",
        "VAEP/90",
        "Off. VAEP/90",
        "Def. VAEP/90",
        "DEFCON",
        "DEFCON/90",
        "Percentile Rank",
    ],
    "Player-Similarity": ["Cosine Distance", "Behavioral Vector", "Statistical Vector"],
    "Goalkeeper-Analytics": [
        "PSxG (Post-Shot Expected Goals)",
        "Goals Prevented",
        "Save %",
        "Launch Rate",
        "xT / Pass (Distribution)",
        "Claim Success %",
        "Sweeper Distance",
        "Outside Box/90",
    ],
    "Movement-Pressing": ["PPDA", "xT (Expected Threat)", "Off-Ball xT", "Pitch Control"],
    "Pitch-Control": ["Pitch Control"],
    "Pass-Timing": ["PAUSA", "Temporal Judgment", "Spatial Selection", "OBSO", "Passes with Value"],
    "Defensive-Impact": ["DEFCON", "Intercept", "Concede", "Disturb", "Deter", "Percentile Rank"],
    "Team-Shape": [
        "Team Shape",
        "Convex Hull",
        "Stretch Index",
        "EFPI",
        "Shape Graph",
        "Defensive Line Height",
        "Inter-Line Gaps",
        "Team Length",
        "Team Width",
    ],
    "Tactical-Positions": [
        "Shape Graph",
        "Position Label",
        "Vertical Level",
        "Horizontal Level",
        "EFPI",
        "Position Map",
        "Formation Detector",
    ],
    "AI-ML-Workflows": [
        "Cost Tier",
        "Freshness SLA",
        "Workflow Card",
        "Workflow Status",
        "Trigger",
        "Cold Start",
        "Entities",
    ],
    "Conversion-Funnel": ["A3 Entry", "Conversion Rate", "Possession"],
}


def _build_glossary_panels() -> str:
    """Generate all per-page glossary panels from PAGE_TERMS + GLOSSARY data.

    Output contains single braces {…} for Taipy bindings. This string is
    injected into build_root_page() via string concatenation (NOT f-string
    interpolation) to preserve the single braces for Taipy.
    """
    parts: list[str] = []
    for page_key, terms in PAGE_TERMS.items():
        filtered = {k: v for k, v in GLOSSARY.items() if k in terms}
        parts.append(f'<|part|render={{show_glossary and current_page == "{page_key}"}}|class_name=ll-dropdown|')
        if not filtered:
            parts.append("*No domain-specific terms on this page.*")
        else:
            for k, v in filtered.items():
                parts.append(f"**{k}** \u2014 {v}")
                parts.append("")
        parts.append("|>")
        parts.append("")
    return "\n".join(parts)


_glossary_panels = _build_glossary_panels()

# fmt: off
_COMP_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary", "Player-Impact", "Player-Comparison", "Goalkeeper-Analytics", "Conversion-Funnel")
_TEAM_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary", "Player-Impact", "Player-Comparison", "Conversion-Funnel")
_MATCH_PAGES = ("Pass-Map", "Pass-Network", "Match-Summary", "Player-Impact", "Conversion-Funnel")
_PLAYER_PAGES = ("Shot-Map", "Heat-Map", "Player-Impact")
_PLAYER_MULTI_PAGES = ("Player-Comparison",)
_XG_MODEL_PAGES = ("Shot-Map",)
_MIN_PASSES_PAGES = ("Pass-Network",)
_MIN_MINUTES_PAGES = ("Player-Impact", "Player-Comparison")
_GK_PAGES = ("Goalkeeper-Analytics",)
_TRACKING_PROVIDER_PAGES = ("Pitch-Control",)
_SUB_VIEW_PAGES = ("Player-Impact", "Movement-Pressing", "Team-Shape", "Goalkeeper-Analytics", "Tactical-Positions")
_PASS_OVERLAY_PAGES = ("Pass-Map",)
_SIMILARITY_PAGES = ("Player-Similarity",)
_PASS_TIMING_PAGES = ("Pass-Timing",)
_DEFCON_PAGES = ("Defensive-Impact",)
_PC_CONTROL_PAGES = ("Pitch-Control",)
_TEAM_SHAPE_PAGES = ("Team-Shape",)
_TACTICAL_POSITIONS_PAGES = ("Tactical-Positions",)
_WF_PAGES = ("AI-ML-Workflows",)
_CONVERSION_FUNNEL_PAGES = ("Conversion-Funnel",)
_FILTER_HEADER_PAGES = ("Shot-Map", "Pass-Map", "Heat-Map", "Pass-Network", "Match-Summary",
                        "Player-Impact", "Player-Comparison", "Goalkeeper-Analytics", "Movement-Pressing",
                        "Pitch-Control", "Team-Shape", "Tactical-Positions", "Pass-Timing",
                        "Defensive-Impact", "AI-ML-Workflows", "Conversion-Funnel")
# fmt: on

# ---------------------------------------------------------------------------
# Sidebar widget definitions — DATA ONLY, zero styling.
# build_sidebar_section() handles all structural wrapping and CSS.
# ---------------------------------------------------------------------------

_FILTER_WIDGETS: list[SidebarWidget] = [
    # Analytical lens choices — before data-scoping filters (no data dependency)
    SidebarWidget(
        "dropdown",
        "selected_xg_model",
        "xG Model",
        "on_xg_model_change",
        condition=f"current_page in {_XG_MODEL_PAGES}",
        lov="xg_model_lov",
        help="StatsBomb: provider xG. v2 Set Encoder: lakehouse Deep Sets model with MC dropout 95% CI (Gal & Ghahramani 2016). Range 0-1, higher = better chance.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_sub_view",
        "View",
        "on_sub_view_change",
        condition=f"current_page in {_SUB_VIEW_PAGES}",
        lov="sub_view_lov",
        help="Switch between analytical views for this page. Each view shows different metrics and visualizations.",
    ),
    # Data-scoping cascade
    SidebarWidget(
        "dropdown",
        "selected_competition",
        "Competition",
        "on_competition_change",
        condition=f"current_page in {_COMP_PAGES}",
        lov="competition_lov",
        help="Filter to a specific league/tournament. All downstream filters (team, match, player) update automatically.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_team",
        "Team",
        "on_team_change",
        condition=f"current_page in {_TEAM_PAGES}",
        lov="team_lov",
        depends_on="selected_competition",
        required=False,
        help="Filter to a specific team within the selected competition.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_match",
        "Match",
        "on_match_change",
        condition=f"current_page in {_MATCH_PAGES}",
        lov="match_lov",
        depends_on="selected_competition",
        help="Select a specific match. Shows date and opponent. Setting Team first narrows this list.",
    ),
    SidebarWidget(
        "dropdown",
        "cf_selected_game_state",
        "Game State",
        "on_cf_game_state_change",
        condition=f"current_page in {_CONVERSION_FUNNEL_PAGES}",
        lov="cf_game_state_lov",
        required=False,
        help="Filter by game state at the time of each action: winning, losing, or drawing. Based on the cumulative scoreline.",
    ),
    SidebarWidget(
        "combobox",
        "selected_player",
        "Player",
        "on_player_change",
        condition=f"current_page in {_PLAYER_PAGES}",
        lov="player_lov",
        depends_on="selected_competition",
        required=False,
        search_var="player_search_query",
        on_search_change="on_player_search_change",
        search_label="Search players",
        help="Optional player filter. Type to search any player in scope; pick from the dropdown to filter the page.",
    ),
    SidebarWidget(
        "dropdown_multi",
        "selected_players_multi",
        "Players (1-3)",
        "on_player_change",
        condition=f"current_page in {_PLAYER_MULTI_PAGES}",
        lov="player_lov_multi",
        depends_on="selected_competition",
        help="Select 1-3 players to compare side-by-side on the radar chart.",
    ),
    SidebarWidget(
        "dropdown_multi",
        "pr_selected_metrics",
        "Metrics",
        "on_pr_metric_change",
        condition=f"current_page in {('Player-Comparison',)}",
        lov="pr_metric_lov",
        depends_on="selected_competition",
        help="Per-90 stats: Goals, xG, Passes, Pass%, VAEP (action value), DEFCON (defensive pressure). See Glossary for definitions.",
    ),
    SidebarWidget(
        "slider",
        "min_passes",
        "Min. passes per connection",
        "on_min_passes_change",
        condition=f"current_page in {_MIN_PASSES_PAGES}",
        slider_min="1",
        slider_max="10",
        slider_range_labels=("1", "10"),
        help="Minimum completed passes between two players to show a connection line. Higher = fewer, stronger links.",
    ),
    SidebarWidget(
        "slider",
        "min_minutes",
        "Min. minutes played",
        "on_min_minutes_change",
        condition=f"current_page in {_MIN_MINUTES_PAGES}",
        slider_min="0",
        slider_max="2000",
        slider_step="45",
        slider_range_labels=("0", "2000"),
        depends_on="selected_competition",
        help="Minimum total minutes played to include a player in rankings. Filters low-sample entries.",
    ),
    # Goalkeeper Analytics — coverage-aware Team selector (replaces the shared
    # Team dropdown on this page; only teams with GK stats for the selected
    # competition appear, per fix/gk-team-coverage-filter).
    SidebarWidget(
        "dropdown",
        "gk_selected_team",
        "Team",
        "gk_on_gk_team_change",
        condition=f"current_page in {_GK_PAGES}",
        lov="gk_team_lov",
        depends_on="selected_competition",
        required=False,
        help=(
            "Only teams with StatsBomb GK event data for the selected competition "
            "are listed. Coverage is uneven in the open dataset — e.g., the Premier "
            "League shows Leicester City 2015/16 fully plus scattered matches from "
            "other clubs, so Manchester United and Liverpool may not appear."
        ),
    ),
    # Goalkeeper Analytics — GK-only player selector + min minutes
    SidebarWidget(
        "combobox",
        "gk_selected_player",
        "Goalkeeper",
        "gk_on_gk_player_change",
        condition=f"current_page in {_GK_PAGES} and selected_sub_view != 'Rankings'",
        lov="gk_player_lov",
        depends_on="selected_competition",
        search_var="gk_player_search_query",
        on_search_change="gk_on_gk_player_search_change",
        search_label="Search goalkeepers",
        help="Select a goalkeeper to view their shot stopping and distribution. Only goalkeepers with GK stats are listed.",
    ),
    SidebarWidget(
        "slider",
        "min_minutes",
        "Min. minutes played",
        "on_min_minutes_change",
        condition=f"current_page in {_GK_PAGES}",
        slider_min="0",
        slider_max="2000",
        slider_step="45",
        slider_range_labels=("0", "2000"),
        depends_on="selected_competition",
        help="Minimum total minutes played to include a GK in rankings. Filters low-sample entries.",
    ),
    SidebarWidget(
        "toggle",
        "pm_show_progressive",
        "Progressive passes",
        "on_pm_toggle_change",
        condition=f"current_page in {_PASS_OVERLAY_PAGES}",
        help="Highlight passes that move the ball significantly closer to the opponent goal.",
    ),
    SidebarWidget(
        "toggle",
        "pm_show_line_breaking",
        "Line-breaking passes",
        "on_pm_toggle_change",
        condition=f"current_page in {_PASS_OVERLAY_PAGES}",
        help="Highlight passes that penetrate at least one defensive line (detected via Ward clustering on 360 freeze frames).",
    ),
    # Tracking / provider
    SidebarWidget(
        "dropdown",
        "selected_provider",
        "Provider",
        "on_provider_change",
        condition=f"current_page in {_TRACKING_PROVIDER_PAGES}",
        lov="provider_lov",
        help="Tracking data source: Metrica (3 matches, 25fps), IDSSE/Bundesliga (7 matches, 25fps), SkillCorner (10 matches, 10fps).",
    ),
    SidebarWidget(
        "dropdown",
        "selected_tracking_match",
        "Tracking Match",
        "on_tracking_match_change",
        condition=f"current_page in {_TRACKING_PROVIDER_PAGES}",
        lov="tracking_match_lov",
        depends_on="selected_provider",
        help="Select a match with tracking data. Only 20 matches across all providers have positional data.",
    ),
    # Movement-specific: view-dependent widget visibility.
    # PPDA sub-view uses Competition; Physical/Off-Ball xT use Provider + Tracking Match.
    # These duplicate the shared widgets with Movement-specific render conditions.
    SidebarWidget(
        "dropdown",
        "selected_competition",
        "Competition",
        "on_competition_change",
        condition='current_page == "Movement-Pressing" and selected_sub_view == "PPDA / Pressing Intensity"',
        lov="competition_lov",
        help="Filter PPDA data to a specific league/tournament.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_provider",
        "Provider",
        "on_provider_change",
        condition='current_page == "Movement-Pressing" and selected_sub_view is not None and selected_sub_view != "PPDA / Pressing Intensity"',
        lov="provider_lov",
        help="Tracking data source for physical/xT metrics.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_tracking_match",
        "Tracking Match",
        "on_tracking_match_change",
        condition='current_page == "Movement-Pressing" and selected_sub_view is not None and selected_sub_view != "PPDA / Pressing Intensity"',
        lov="tracking_match_lov",
        depends_on="selected_provider",
        help="Select a tracking match for physical/xT analysis.",
    ),
    SidebarWidget(
        "dropdown",
        "ma_physical_metric",
        "Metric",
        "on_ma_physical_metric_change",
        lov="ma_physical_metric_lov",
        condition='current_page == "Movement-Pressing" and selected_sub_view == "Physical Performance"',
        help="Physical metric to display: total distance, high-speed running (over 5.5 m/s), sprint count, or sprint distance.",
    ),
    # Pass Timing
    SidebarWidget(
        "dropdown",
        "pt_selected_match",
        "PAUSA Match",
        "pt_on_match_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_match_lov",
        help="PAUSA pass timing is available for 7 IDSSE Bundesliga matches with ELASTIC-synced tracking data.",
    ),
    SidebarWidget(
        "dropdown",
        "pt_selected_team",
        "Team",
        "pt_on_team_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_team_lov",
        depends_on="pt_selected_match",
        required=False,
        help="Filter to a specific team's passes. Leave blank for all.",
    ),
    SidebarWidget(
        "combobox",
        "pt_selected_player",
        "Player",
        "pt_on_player_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        lov="pt_player_lov",
        depends_on="pt_selected_match",
        required=False,
        search_var="pt_player_search_query",
        on_search_change="pt_on_player_search_change",
        search_label="Search players",
        help="Filter to a specific player's passes. Leave blank for all.",
    ),
    SidebarWidget(
        "slider",
        "pt_per_match_min_passes",
        "Min. passes (per match)",
        "pt_on_per_match_min_passes_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        slider_min="1",
        slider_max="50",
        slider_range_labels=("1", "50"),
        help="Minimum passes in a single match to include a player-match row in per-match rankings. Filters low-sample entries.",
    ),
    SidebarWidget(
        "slider",
        "pt_min_passes_with_value",
        "Min. passes with value",
        "pt_on_min_passes_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        slider_min="1",
        slider_max="200",
        slider_range_labels=("1", "200"),
        help="Minimum passes where actual OBSO is above zero (quality proxy). Filters aggregate rankings to players with enough meaningful passes for stable averages.",
    ),
    SidebarWidget(
        "slider",
        "pt_min_minutes",
        "Min. minutes played",
        "pt_on_min_minutes_change",
        condition=f"current_page in {_PASS_TIMING_PAGES}",
        slider_min="0",
        slider_max="1000",
        slider_step="45",
        slider_range_labels=("0", "1000"),
        help="Minimum total minutes played across all matches. Filters aggregate rankings to exclude players with minimal playing time.",
    ),
    # Defensive Impact — View first (analytical lens), then data-scoping
    SidebarWidget(
        "dropdown",
        "dv_current_view",
        "View",
        "dv_on_view_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_view_lov",
        help="Rankings: league-wide leaderboard. Breakdown: per-category stacked bar for one player. Timeline: match-level pressure events.",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_comp",
        "Competition (DEFCON)",
        "dv_on_comp_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_comp_lov",
        help="DEFCON data uses StatsBomb 360 freeze frames. Only competitions with 360 coverage have defensive credit data.",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_team",
        "Team",
        "dv_on_team_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_team_lov",
        depends_on="dv_selected_comp",
        required=False,
        help="Filter rankings or breakdown to a specific team.",
    ),
    SidebarWidget(
        "combobox",
        "dv_selected_breakdown_player",
        "Player",
        "dv_on_breakdown_player_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_breakdown_player_lov",
        depends_on="dv_current_view",
        depends_value="Breakdown",
        depends_lov_populated=True,
        search_var="dv_breakdown_player_search_query",
        on_search_change="dv_on_breakdown_player_search_change",
        search_label="Search players",
        help="Select a player to see their DEFCON credit breakdown (Intercept, Concede, Disturb, Deter).",
    ),
    SidebarWidget(
        "combobox",
        "dv_selected_timeline_player",
        "Player",
        "dv_on_timeline_player_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_timeline_player_lov",
        depends_on="dv_current_view",
        depends_value="Timeline",
        depends_lov_populated=True,
        search_var="dv_timeline_player_search_query",
        on_search_change="dv_on_timeline_player_search_change",
        search_label="Search players",
        help="Select a player to view their match-by-match pressure timeline.",
    ),
    SidebarWidget(
        "dropdown",
        "dv_selected_timeline_match",
        "Match",
        "dv_on_timeline_match_change",
        condition=f"current_page in {_DEFCON_PAGES}",
        lov="dv_timeline_match_lov",
        depends_on="dv_current_view",
        depends_value="Timeline",
        depends_lov_populated=True,
        help="Select a match to see minute-by-minute defensive pressure events.",
    ),
    # --- Operations page filters (AI/ML Workflows) ---
    # These filter by workflow metadata (type, runtime, freshness) rather than
    # analytical data dimensions (competition, team, match). They only appear
    # on the AI-ML-Workflows page.
    SidebarWidget(
        "dropdown",
        "wf_type_filter",
        "Workflow Type",
        "wf_on_type_filter",
        condition=f"current_page in {_WF_PAGES}",
        lov="wf_type_lov",
        help="Filter by workflow type: Train+Infer, Grid Compute, Heuristic, Ingestion, Data Movement, Validation.",
    ),
    SidebarWidget(
        "dropdown",
        "wf_runtime_filter",
        "Runtime",
        "wf_on_runtime_filter",
        condition=f"current_page in {_WF_PAGES}",
        lov="wf_runtime_lov",
        help="Filter by execution runtime: Databricks (DB), HuggingFace Jobs (HF), or both.",
    ),
    SidebarWidget(
        "dropdown",
        "wf_freshness_filter",
        "Freshness",
        "wf_on_freshness_filter",
        condition=f"current_page in {_WF_PAGES}",
        lov="wf_freshness_lov",
        help="Filter by data freshness status: OK (within SLA), Warning (approaching), Stale (exceeded).",
    ),
    # Pitch Control
    SidebarWidget(
        "dropdown",
        "pc_half",
        "Half",
        "pc_on_half_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
        lov="pc_half_lov",
        depends_on="selected_tracking_match",
        help="Select 1st or 2nd half of the match.",
    ),
    SidebarWidget(
        "dropdown",
        "pc_model",
        "Model",
        "pc_on_model_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
        lov="pc_model_lov",
        depends_on="selected_tracking_match",
        help="Spearman (2017): physics-based model using player positions, velocities, and time-to-intercept. Voronoi: geometric nearest-player assignment.",
    ),
    SidebarWidget(
        "toggle",
        "pc_show_velocity",
        "Show velocity arrows",
        "pc_on_velocity_change",
        condition=f"current_page in {_PC_CONTROL_PAGES}",
        depends_on="selected_tracking_match",
        help="Display player velocity vectors as arrows on the pitch. Arrow length indicates speed.",
    ),
    SidebarWidget(
        "slider",
        "pc_elapsed_seconds",
        "Time",
        "pc_on_seconds_change",
        condition=f"current_page in {_PC_CONTROL_PAGES} and pc_max_seconds > 1",
        slider_min="0",
        slider_max="2700",
        filter_box_label="<|{pc_time_label}|text|raw|>",
        slider_range_labels=("0:00", ""),
        slider_range_vars=("", "pc_max_time_display"),
        change_delay=300,
    ),
    # Team Shape — Provider + Tracking Match (duplicated with Team-Shape condition)
    SidebarWidget(
        "dropdown",
        "selected_provider",
        "Provider",
        "on_provider_change",
        condition=f"current_page in {_TEAM_SHAPE_PAGES}",
        lov="provider_lov",
        help="Tracking data source for team shape analysis.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_tracking_match",
        "Tracking Match",
        "on_tracking_match_change",
        condition=f"current_page in {_TEAM_SHAPE_PAGES}",
        lov="tracking_match_lov",
        depends_on="selected_provider",
        help="Select a tracking match for shape analysis.",
    ),
    SidebarWidget(
        "dropdown",
        "ts_selected_team",
        "Team",
        "ts_on_team_change",
        condition=f"current_page in {_TEAM_SHAPE_PAGES}",
        lov="ts_team_lov",
        depends_on="selected_tracking_match",
        help="Select home or away team for shape analysis.",
    ),
    SidebarWidget(
        "dropdown",
        "ts_selected_half",
        "Half",
        "ts_on_half_change",
        condition='current_page == "Team-Shape" and selected_sub_view == "Snapshot"',
        lov="ts_half_lov",
        depends_on="selected_tracking_match",
        help="Filter snapshot by match period. 'Full Match' averages both halves (Phase Average mode). In single-frame mode, 1st Half is used.",
    ),
    SidebarWidget(
        "toggle",
        "ts_phase_average",
        "Phase Average",
        "ts_on_phase_toggle",
        condition='current_page == "Team-Shape" and selected_sub_view == "Snapshot"',
        help="Toggle between single-frame view and phase-averaged positions.",
    ),
    SidebarWidget(
        "slider",
        "ts_elapsed_seconds",
        "Time",
        "ts_on_seconds_change",
        condition='current_page == "Team-Shape" and selected_sub_view == "Snapshot" and not ts_phase_average and ts_max_seconds > 1',
        slider_min="0",
        slider_max="2700",
        filter_box_label="<|{ts_time_label}|text|raw|>",
        slider_range_labels=("0:00", ""),
        slider_range_vars=("", "ts_max_time_display"),
        change_delay=300,
        help="Scrub through match time to view team shape at a specific moment.",
    ),
    SidebarWidget(
        "toggle",
        "ts_show_hull",
        "Show Hull",
        "ts_on_hull_toggle",
        condition='current_page == "Team-Shape" and selected_sub_view == "Snapshot"',
        help="Toggle convex hull overlay showing team territorial extent.",
    ),
    SidebarWidget(
        "toggle",
        "ts_show_formation_lines",
        "Show Lines",
        "ts_on_formation_lines_toggle",
        condition='current_page == "Team-Shape" and selected_sub_view == "Snapshot"',
        help="Toggle dashed formation lines connecting players by detected line clusters.",
    ),
    # Tactical Positions — Provider + Tracking Match + Team + Player selectors
    SidebarWidget(
        "dropdown",
        "selected_provider",
        "Provider",
        "on_provider_change",
        condition=f"current_page in {_TACTICAL_POSITIONS_PAGES}",
        lov="provider_lov",
        help="Tracking data source for tactical position analysis.",
    ),
    SidebarWidget(
        "dropdown",
        "selected_tracking_match",
        "Tracking Match",
        "on_tracking_match_change",
        condition=f"current_page in {_TACTICAL_POSITIONS_PAGES}",
        lov="tracking_match_lov",
        depends_on="selected_provider",
        help="Select a tracking match for position detection.",
    ),
    SidebarWidget(
        "dropdown",
        "tac_selected_team",
        "Team",
        "tac_on_team_change",
        condition=f"current_page in {_TACTICAL_POSITIONS_PAGES}",
        lov="tac_team_lov",
        depends_on="selected_tracking_match",
        help="Select home or away team for position analysis.",
    ),
    SidebarWidget(
        "combobox",
        "tac_selected_player",
        "Player",
        "tac_on_player_change",
        condition='current_page == "Tactical-Positions" and selected_sub_view == "Position Maps"',
        lov="tac_player_lov",
        depends_on="tac_selected_team",
        search_var="tac_player_search_query",
        on_search_change="tac_on_player_search_change",
        search_label="Search players",
        help="Select a player to view their 5x5 position map heatmap.",
    ),
    SidebarWidget(
        "combobox",
        "tac_selected_compare_player",
        "Compare with",
        "tac_on_compare_player_change",
        condition='current_page == "Tactical-Positions" and selected_sub_view == "Position Maps"',
        lov="tac_compare_player_lov",
        depends_on="tac_selected_team",
        search_var="tac_compare_player_search_query",
        on_search_change="tac_on_compare_player_search_change",
        search_label="Search players",
        help="Select a second player to compare position maps side by side.",
    ),
]

_SEARCH_WIDGETS: list[SidebarWidget] = [
    SidebarWidget(
        "dropdown",
        "ps_search_mode",
        "Search by",
        "on_ps_search_mode_change",
        lov="ps_search_mode_lov",
        help="Playing style: 192-d transformer embedding from match action sequences (adversarially debiased). Statistical output: 13-d z-score vector from per-90 stats.",
    ),
    SidebarWidget(
        "combobox",
        "ps_selected_player",
        "Player",
        "on_ps_selected_player_change",
        lov="ps_player_lov",
        search_var="ps_player_search_query",
        on_search_change="on_ps_player_search_change",
        search_label="Search players",
        help="Type to search ~8,950 players. Select one to find similar players by embedding distance.",
    ),
    SidebarWidget(
        "dropdown",
        "ps_result_count",
        "Results",
        "on_ps_result_count_change",
        lov="ps_result_count_lov",
        help="Number of similar players to return (5-50).",
    ),
    SidebarWidget(
        "toggle",
        "ps_filter_by_competition",
        "Filter by competition",
        "on_ps_filter_by_competition_change",
        help="When enabled, restrict similarity search to players within a specific competition.",
    ),
    SidebarWidget(
        "dropdown",
        "ps_selected_competition",
        "Competition",
        "on_ps_selected_competition_change",
        condition="ps_filter_by_competition",
        lov="ps_competition_lov",
        help="Restrict similarity search to players within this competition.",
    ),
    SidebarWidget(
        "slider",
        "ps_min_matches",
        "Min. matches",
        "on_ps_min_matches_change",
        slider_min="1",
        slider_max="50",
        slider_range_labels=("1", "50"),
        help="Minimum matches played to include a player in results. Higher = more robust embeddings.",
    ),
    # Compare with — appears after results load (depends_lov_populated gates visibility)
    SidebarWidget(
        "dropdown",
        "ps_selected_compare",
        "Compare with",
        "on_ps_selected_compare_change",
        lov="ps_compare_lov",
        depends_lov_populated=True,
    ),
]

# Generate sidebar sections from widget definitions
_filter_section = build_sidebar_section(
    "Filters", _FILTER_WIDGETS, condition=f"current_page in {_FILTER_HEADER_PAGES}", f_string=False
)
_search_section = build_sidebar_section(
    "Search", _SEARCH_WIDGETS, condition=f"current_page in {_SIMILARITY_PAGES}", f_string=False
)


def build_root_page(nav_md: str) -> str:
    """Build the root page shell with generated navigation.

    Args:
        nav_md: Generated navigation markdown from build_nav().
    """
    return (
        f"""
<|layout|columns=300px 1fr|gap=0.75rem|

<|part|class_name=sidebar|

{nav_md}

{_filter_section}
{_search_section}

|>

<|part|

<|part|class_name=ll-title-row|
<|layout|columns=1fr auto auto|gap=0.5rem|class_name=align-columns-center|

<|part|class_name=ll-brand|
# <span class="material-symbols-outlined">sports_soccer</span> (Right! Luxury!) Lakehouse
|>

<|Glossary|button|class_name=text-no-transform ll-header-btn ll-btn-glossary|on_action=toggle_glossary|>

<|Getting Started|button|class_name=text-no-transform ll-header-btn ll-btn-started|on_action=toggle_getting_started|>

|>
|>

"""
        + _glossary_panels
        + f"""

<|part|render={{show_getting_started}}|class_name=ll-dropdown|
{GETTING_STARTED}
|>

<|part|render={{is_loading}}|class_name=ll-loading-overlay|
<|part|class_name=ll-loading-spinner|
<span class="material-symbols-outlined ll-spin">progress_activity</span>

<|{{loading_text}}|text|raw|>
|>
|>

<|content|>

<|part|render={{show_site_footer}}|class_name=ll-footer|
{_FOOTER_CONTENT}
|>

|>

|>
"""
    )
