# Structurizr DSL — (Right! Luxury!) Lakehouse Soccer Analytics Platform
# Auto-generated by mad-scientist-skills:c4 + final-review (2026-04-29, PR-LL2 cycle close).
# Refresh after each major architectural change (new container, new external system,
# changed data flow). Keep in sync with ARCHITECTURE.md.
#
# 2026-04-29 review (PR-LL2): SPADL post-conversion enrichment + 4-source coverage
# (StatsBomb / Wyscout / IDSSE / Metrica) modifies the ingestion pipeline INTERNALS
# inside the existing ingestionJobs container; no new architectural element. ADR-016
# documents the named ``apply_spadl_enrichments`` stage + canonical/native naming
# convention. ADR-011's ``(provider, native_id)`` join pattern extended into bronze
# (5 new ``*_native`` STRING columns on bronze.spadl_actions + bronze.vaep_action_values)
# — captured in the existing bronzeDelta + goldMarts containers' descriptions. silly-kicks
# 1.7.0+ ``sportec`` / ``metrica`` dedicated DataFrame converters wired in alongside the
# pre-existing statsbomb / wyscout paths.
#
# 2026-04-28 review: PR 7 ADR-011 staged Kimball migration is now complete (PR 1–7
# all shipped + deployed; PR 8 locked to 2026-07-22 cleanup). PR 7's ADR-013
# second application (fct_pausa_values mart) is reflected in the existing dbtProject
# + goldMarts containers — no structural change. Phase 2 HF artifact republish chain
# is captured in the existing ingestionJobs -> hfHub + mlTraining -> hfHub edges.
# A new local-execution PEP 723 publisher (scripts/publish_shots_on_target_hf.py)
# was added in this cycle; it lives inside the wheelLib + ingestionJobs containers
# (no new architectural element).

workspace "Luxury Lakehouse" "Serverless soccer analytics platform: multi-provider event/tracking ingestion → Kimball-conformed warehouse → ML inference → Taipy dashboard + HF datasets/models." {

    model {
        # ── People ────────────────────────────────────────────────────
        analyst = person "Analyst / End User" "Browses the Taipy dashboard for tactical metrics (xG, VAEP, line-breaking, PAUSA, formations). Optionally pulls HF datasets/models for offline analysis."
        operator = person "Operator (Karsten)" "Develops, deploys, monitors. Triggers ingestion + dbt builds, reviews CI, manages workflow cards + ADRs."

        # ── External systems ────────────────────────────────────────────
        statsbombSrc = softwareSystem "StatsBomb Open Data" "GitHub-hosted JSON event data + 360 freeze frames (~3500 matches across PL/La Liga/CL/WC)." "External"
        wyscoutSrc = softwareSystem "Wyscout Public Dataset" "Figshare-hosted JSON event data (~1900 matches)." "External"
        idsseSrc = softwareSystem "IDSSE Open Data (DFL Bundesliga)" "Figshare-hosted DFL Match Information XML + Position XML + Event XML (7 matches with synchronised event+tracking)." "External"
        metricaSrc = softwareSystem "Metrica Sports Sample Data" "GitHub-hosted anonymised tracking + events (3 sample matches)." "External"
        skillcornerSrc = softwareSystem "SkillCorner Broadcast Tracking" "kloppy-loaded broadcast-only tracking (~250 matches, no event data)." "External"
        hfHub = softwareSystem "HuggingFace Hub" "Org `luxury-lakehouse` hosts 19 datasets (events, tracking, predictions) + 17 model cards + 1 Taipy Space + 1 ScoutGPT inference Space." "External"
        hfJobs = softwareSystem "HuggingFace Jobs" "On-demand GPU compute for ML training (xG v2, ScoutGPT, Football2Vec, OBSO surfaces). L40Sx1 default; one-off scripts via PEP 723 `uv run`." "External"
        databricksWs = softwareSystem "Databricks Workspace" "Hosts Unity Catalog (`soccer_analytics`) + Lakebase + Jobs Serverless + SQL Warehouse + MLflow registry." "External"
        awsCloud = softwareSystem "AWS (us-east-1)" "Terraform state bucket (KMS-encrypted) + IAM OIDC trust for GitHub Actions + AWS Budgets." "External"
        githubActions = softwareSystem "GitHub Actions" "CI: ruff, pyright, dbt parse, dbt slim/full builds (live-CI on PR), wheel build + upload to Databricks Volume on push to main." "External"
        openrouter = softwareSystem "OpenRouter / Anthropic / OpenAI / Local LLMs" "LLM gateway for Evolve Engine (architecture exploration), Mad Scientist audit skills, ml-intern. Local LLMs via DGX Spark (Llama 3.3 70B Q4)." "External"

        # ── The system ──────────────────────────────────────────────────
        lakehouse = softwareSystem "(Right! Luxury!) Lakehouse" "Multi-provider soccer analytics platform" {

            # ── Containers ─────────────────────────────────────────────
            taipyApp = container "Taipy Web Application" "16-page interactive dashboard: Pass Map, Heat Map, xG, VAEP, Line Breaking, Formations, Pass Timing, etc. Reads Lakebase synced tables for sub-100ms queries." "Python 3.10, Taipy 4.1, ll_ext, plotly" "WebApp"
            scoutgptSpace = container "ScoutGPT Inference Space" "Per-pass counterfactual ranking + sequence completion. Currently disabled at runtime; weights published as HF model artifact." "Python 3.10, PyTorch 2.5, transformers" "WebApp"
            wheelLib = container "luxury-lakehouse Wheel" "Single deployable Python wheel (~600 modules) carrying ingestion + analytics + workflows + shared. Built by hatchling, force-includes dbt project + HF cards. Auto-uploaded to UC Volume on push to main." "Python 3.10 wheel" "Library"
            ingestionJobs = container "Ingestion + Compute Pipelines" "27 workflow-card-defined jobs running on Databricks Serverless. Per-provider ingestion (statsbomb/wyscout/idsse/metrica/skillcorner) + per-method compute (pitch control, OBSO, PAUSA, DEFCON, line-breaking, off-ball xT, space creation, formations, ScoutGPT/Football2Vec/xG inference). `applyInPandas` distribution." "Python wheel on Databricks Jobs Serverless" "JobRunner"
            mlTraining = container "ML Training Jobs" "PEP 723 `uv run` scripts on HF Jobs L40Sx1: xG v2 (Deep Sets + MC dropout), ScoutGPT (Doc2Vec/Word2Vec/transformer), Football2Vec (gensim → in-house), VAEP (silly-kicks), OBSO grids. MLflow `@champion` aliases + UC Volume weights." "Python 3.10 + uv + PEP 723 + HF Jobs" "JobRunner"
            evolveEngine = container "Evolve Engine" "Architecture-exploration framework: pre-registered rules promote/keep/cut variants. Backends: LocalCudaBackend, RemoteSSHBackend (Media-PC + DGX Spark), HF Jobs L40Sx1. Sandboxed AST-allowlist `exec()` per ADR-001." "Python 3.10, JAX, PyTorch, openevolve, openrouter" "JobRunner"
            dbtProject = container "dbt Project" "Silver views + gold marts. ~80 models. ADR-011 Kimball-conformed dim_matches/dim_teams/dim_players/dim_competitions; ADR-013 ML inference output marts (fct_xg_predictions_v2, fct_pausa_values). Live-CI on Databricks SQL Warehouse." "dbt-core 1.10–1.12, dbt-databricks, dbt_utils, dbt_expectations" "DbtProject"
            bronzeDelta = container "Bronze Delta Tables" "Raw provider data — events, tracking, freeze frames, matches, teams, players. Schema-on-write with `_ingested_at` audit. Per-provider isolation; Liquid Clustering on match_id." "Delta Lake on Unity Catalog `soccer_analytics.bronze`" "Database"
            silverViews = container "Silver Views (dbt)" "Provider-specific staging views: stg_<provider>__<table>. Type-cast + dedup + bronze-completeness passthroughs. Materialized as views in `soccer_analytics.dev_silver`." "dbt-core view materialization" "Database"
            goldMarts = container "Gold Marts (dbt)" "Conformed-fact marts (fct_passes, fct_shots, fct_action_values, fct_match_summary, fct_player_stats, fct_pausa_values, etc.) + dimensions (dim_matches, dim_teams, dim_players, dim_competitions). All migrated to Kimball surrogate FKs (match_key/team_key/player_key) per ADR-011." "Delta Lake on Unity Catalog `soccer_analytics.dev_gold`" "Database"
            lakebase = container "Lakebase (PostgreSQL)" "Synced tables (read replica of Delta marts) on managed Postgres. Custom indexes via `scripts/create_indexes.py` for sub-100ms point lookups from Taipy. ADR-005 grants automation; ADR-002 §4 schema-drift guards." "Lakebase managed PostgreSQL" "Database"
            ucVolume = container "UC Volume / Model Registry" "Per-method model weights (xG v1+v2, VAEP, ScoutGPT, Football2Vec, PSxG, EPV grids) under `/Volumes/soccer_analytics/dev_gold/model_weights/`. MLflow `@champion` aliases per ADR-012 for atomic model promotion." "Unity Catalog Volumes + MLflow" "Database"
            workflowCards = container "Workflow Cards (YAML)" "Per-pipeline operational contract: governance posture, references, inputs/outputs, execution config, performance budgets, cost. 27 cards. Renders in Taipy AI/ML Workflows page; consumed by `wf-dbt-build.yaml` for graph orchestration." "YAML + Pydantic models" "Library"

            # ── External relationships ──────────────────────────────────
            ingestionJobs -> statsbombSrc "Pulls JSON match/event/360 data" "HTTPS"
            ingestionJobs -> wyscoutSrc "Pulls JSON event data" "HTTPS"
            ingestionJobs -> idsseSrc "Pulls DFL XML files" "HTTPS"
            ingestionJobs -> metricaSrc "Pulls CSV/JSON sample data" "HTTPS"
            ingestionJobs -> skillcornerSrc "Pulls broadcast tracking via kloppy" "HTTPS"
            ingestionJobs -> hfHub "Publishes datasets via `ingestion.hf_publish`" "huggingface_hub API"
            ingestionJobs -> ucVolume "Reads ML model weights for inference" "Spark"
            mlTraining -> hfHub "Publishes trained model weights" "huggingface_hub API"
            mlTraining -> ucVolume "Uploads weights to UC Volume + sets MLflow champion" "MLflow + Spark"
            evolveEngine -> openrouter "LLM-driven architecture mutation" "litellm/HTTPS"
            evolveEngine -> hfHub "Publishes evolve seed programs + checkpoints" "huggingface_hub API"
            githubActions -> wheelLib "Builds wheel on push to main" "uv build + Databricks SDK"
            githubActions -> awsCloud "Assumes IAM role via OIDC for Terraform" "AWS STS"
            taipyApp -> hfHub "Hosted as luxury-lakehouse Space" "Spaces runtime"
            scoutgptSpace -> hfHub "Hosted as inference Space" "Spaces runtime"
            analyst -> taipyApp "Browses match analytics" "HTTPS via HF Spaces"
            analyst -> hfHub "Downloads datasets/models" "huggingface_hub"
            operator -> githubActions "Pushes commits, opens PRs" "git/HTTPS"
            operator -> databricksWs "Triggers jobs, reviews dbt + Lakebase" "Databricks UI/SDK"
            operator -> evolveEngine "Runs evolve cycles" "CLI"

            # ── Internal relationships ───────────────────────────────────
            ingestionJobs -> bronzeDelta "Writes raw provider data" "Delta MERGE/append"
            ingestionJobs -> goldMarts "Writes ML inference outputs to dev_gold (legacy direct-write being retired per ADR-013)" "Delta replaceWhere"
            mlTraining -> bronzeDelta "Reads training inputs (events, tracking, freeze frames)" "Spark"
            dbtProject -> bronzeDelta "Reads via source declarations" "Spark SQL"
            dbtProject -> silverViews "Builds (materialized views)" "dbt run"
            dbtProject -> goldMarts "Builds (incremental + table marts)" "dbt run"
            silverViews -> bronzeDelta "Reads bronze sources" "view definition"
            goldMarts -> silverViews "Reads silver views" "view + mart joins"
            goldMarts -> lakebase "Synced via Databricks Lakebase Sync" "managed sync"
            taipyApp -> lakebase "Reads synced marts via psycopg + connection pool" "PostgreSQL/TCP"
            taipyApp -> workflowCards "Reads + renders AI/ML Workflows page from YAML" "Pydantic models"
            workflowCards -> dbtProject "wf-dbt-build.yaml enumerates every dbt mart" "YAML"
            ingestionJobs -> workflowCards "Reads governance + execution config" "Pydantic load"
            wheelLib -> ingestionJobs "Carries Python code (deployed via UC Volume)" "wheel install"
            wheelLib -> mlTraining "Carries shared analytics modules" "uv install via PEP 723"
            wheelLib -> taipyApp "Carries shared modules (compiled into HF Space)" "manage_space.py"
            scoutgptSpace -> ucVolume "Loads ScoutGPT weights at startup" "huggingface_hub mirror"
            evolveEngine -> mlTraining "Dispatches variant evaluations" "Backend abstraction"
        }

        production = deploymentEnvironment "Production" {
            deploymentNode "AWS us-east-1" "Cloud region" "AWS" {
                deploymentNode "Databricks Workspace" "Managed analytics platform" "Databricks" {
                    deploymentNode "Unity Catalog (soccer_analytics)" "Governance layer" "Unity Catalog" {
                        containerInstance bronzeDelta
                        containerInstance silverViews
                        containerInstance goldMarts
                        containerInstance ucVolume
                    }
                    deploymentNode "Jobs Serverless" "Workflow execution" "Serverless compute" {
                        containerInstance ingestionJobs
                    }
                    deploymentNode "Lakebase (managed Postgres)" "Read-replica sync target" "Postgres" {
                        containerInstance lakebase
                    }
                    deploymentNode "SQL Warehouse" "dbt + ad-hoc queries" "Serverless SQL" {
                        infrastructureNode "dbt build runner" "Live-CI runs against this warehouse on every PR" "PERFORMANCE_OPTIMIZED"
                    }
                }
                deploymentNode "S3 + KMS" "Terraform state + secrets" "Managed AWS" {
                    infrastructureNode "TF state bucket" "Encrypted by KMS, IAM-restricted" "S3"
                }
            }
            deploymentNode "HuggingFace" "Hugging Face platform" "HuggingFace" {
                deploymentNode "Spaces" "Hosted apps" "Spaces" {
                    containerInstance taipyApp
                    containerInstance scoutgptSpace
                }
                deploymentNode "Datasets + Models" "Public HF Hub repos" "Hub" {
                    infrastructureNode "luxury-lakehouse org" "19 datasets + 17 model cards" "HF org"
                }
                deploymentNode "Jobs (L40Sx1)" "On-demand GPU" "L40S 48GB" {
                    containerInstance mlTraining
                }
            }
            deploymentNode "Operator workstation + DGX Spark + Media-PC" "Local development + training" "Hybrid" {
                deploymentNode "Windows 11 (Karsten's PC)" "Primary dev box" "RTX 5070 Ti, 96 GB RAM" {
                    infrastructureNode "uv + .venv" "Python 3.10 venv" "Local"
                }
                deploymentNode "DGX Spark (192.168.68.73)" "Local LLM host" "ARM64, 128 GB unified" {
                    infrastructureNode "Llama 3.3 70B Q4" "Local LLM for evolve cycles" "Ollama"
                }
                deploymentNode "Media-PC (192.168.68.70)" "Secondary GPU host" "RTX, SSH-reachable" {
                    containerInstance evolveEngine
                }
            }
        }
    }

    views {
        systemContext lakehouse "SystemContext" {
            include *
            autoLayout
        }

        container lakehouse "Containers" {
            include *
            autoLayout
        }

        deployment lakehouse production "Deployment" {
            include *
            autoLayout
        }

        styles {
            element "Person" {
                shape Person
                background #08427B
                color #ffffff
            }
            element "Software System" {
                background #1168BD
                color #ffffff
            }
            element "External" {
                background #999999
                color #ffffff
            }
            element "Container" {
                background #438DD5
                color #ffffff
            }
            element "Database" {
                shape Cylinder
                background #438DD5
                color #ffffff
            }
            element "WebApp" {
                shape WebBrowser
                background #438DD5
                color #ffffff
            }
            element "JobRunner" {
                shape RoundedBox
                background #2E7D32
                color #ffffff
            }
            element "Library" {
                shape Folder
                background #6A1B9A
                color #ffffff
            }
            element "DbtProject" {
                shape Hexagon
                background #FF8F00
                color #ffffff
            }
            element "Component" {
                background #85BBF0
                color #000000
            }
            relationship "Relationship" {
                color #707070
            }
        }
    }

}
