"""Phase 0 Optuna harness for the ExT v2 reproduction.

Per design spec §6 + locked decision A (single-source ``fct_action_values``,
NLL on ``action_type='pass'`` subset, hash-based 15% match holdout):

1. Split input ``actions`` into train/holdout via deterministic hash on
   ``(competition_id, match_key)``.
2. Filter holdout to passes only (``action_type='pass'``).
3. Run Optuna study with ``direction='minimize'`` and ``n_trials=1`` —
   Phase 0 has no axes active (the objective makes zero
   ``trial.suggest_*`` calls). Phases 1-4 add axes incrementally without
   restructuring the harness.
4. Re-fit ``SinghProducer`` on train and return ``Phase0Result`` exposing
   the best XTGrid, best NLL, study, and dataset metadata.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Final

import optuna
import pandas as pd

from analytics.expected_threat import XTGrid
from analytics.ext_v2.fitness import compute_holdout_nll
from analytics.ext_v2.holdout import DEFAULT_HOLDOUT_FRACTION, holdout_split
from analytics.ext_v2.producer import SinghProducer
from analytics.ext_v2.transition import GridSpec

_HARNESS_REQUIRED_COLUMNS: Final[tuple[str, ...]] = (
    "competition_id",
    "match_key",
    "type_name",
    "result_name",
    "action_type",
    "start_x",
    "start_y",
    "end_x",
    "end_y",
)


@dataclass(frozen=True)
class Phase0Result:
    """End-to-end Phase 0 harness output.

    Attributes:
        best_trial: The Optuna trial with the lowest NLL (Phase 0 has only
            one trial, so this is trivially trial 0).
        best_xt_grid: ``XTGrid`` produced by re-fitting ``SinghProducer``
            on the train fold with the best trial's hyperparameters.
        best_nll: Held-out NLL on the pass-only subset of the holdout fold.
        study: The Optuna study object — exposed for downstream analysis
            (per-trial logs, study.trials_dataframe(), etc.).
        n_train_actions: Row count of the train fold.
        n_holdout_passes: Row count of the pass-only holdout subset.
        producer: The fitted ``SinghProducer`` (exposes
            ``.transition_matrix`` for downstream NLL re-evaluation).
    """

    best_trial: optuna.trial.FrozenTrial
    best_xt_grid: XTGrid
    best_nll: float
    study: optuna.Study
    n_train_actions: int
    n_holdout_passes: int
    producer: SinghProducer


def objective(
    trial: optuna.trial.Trial,
    train_actions: pd.DataFrame,
    holdout_passes: pd.DataFrame,
    *,
    grid: GridSpec,
) -> float:
    """Phase 0 Optuna objective — fits ``SinghProducer``, returns held-out NLL.

    No ``trial.suggest_*`` calls in Phase 0 (no axes active). Phases 1-4
    activate axes via this same function: each phase adds suggests at the
    top, then constructs the appropriate ``Producer`` subclass.
    """
    del trial  # Phase 0: no axes — trial is unused but kept for ABI parity
    producer = SinghProducer(grid=grid).fit(train_actions)
    return compute_holdout_nll(producer, holdout_passes, grid=grid)


def run_phase0_harness(
    actions: pd.DataFrame,
    *,
    grid: GridSpec | None = None,
    holdout_fraction: float = DEFAULT_HOLDOUT_FRACTION,
    n_trials: int = 1,
    study_name: str | None = None,
) -> Phase0Result:
    """Run the Phase 0 ExT v2 harness end-to-end.

    Args:
        actions: SPADL action rows from ``fct_action_values``. Must contain
            ``competition_id, match_key, type_name, result_name, action_type,
            start_{x,y}, end_{x,y}``.
        grid: Pitch-grid binning. Defaults to ``GridSpec()`` (12x8 SPADL).
        holdout_fraction: Fraction of matches to send to holdout via hash
            (default 0.15 per design spec §5.3).
        n_trials: Optuna trials. Phase 0: 1 (no axes). Kept as a parameter
            for forward compatibility with Phases 1-4.
        study_name: Optuna study name. Default: an autogenerated UUID.

    Returns:
        ``Phase0Result`` — see dataclass docstring.

    Raises:
        ValueError: if required columns are missing or ``actions`` is empty.
    """
    missing = [col for col in _HARNESS_REQUIRED_COLUMNS if col not in actions.columns]
    if missing:
        msg = f"actions missing required columns: {missing}"
        raise ValueError(msg)
    if actions.empty:
        msg = "actions is empty — nothing to fit"
        raise ValueError(msg)

    grid = grid if grid is not None else GridSpec()

    train_actions, holdout_actions = holdout_split(actions, holdout_fraction=holdout_fraction)
    holdout_passes = holdout_actions[holdout_actions["action_type"] == "pass"].copy()

    study = optuna.create_study(direction="minimize", study_name=study_name)
    study.optimize(
        lambda trial: objective(trial, train_actions, holdout_passes, grid=grid),
        n_trials=n_trials,
    )

    # Re-fit on train with the best trial's params (Phase 0: no params, so
    # any of the n_trials trials is equivalent — first trial's grid suffices).
    producer = SinghProducer(grid=grid).fit(train_actions)

    return Phase0Result(
        best_trial=study.best_trial,
        best_xt_grid=producer.xt_grid,
        best_nll=study.best_value,
        study=study,
        n_train_actions=len(train_actions),
        n_holdout_passes=len(holdout_passes),
        producer=producer,
    )
